/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
  const UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  const UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.4_@tiptap+core@3.20.4_@tiptap+pm@3.20.4__@tiptap_d86545d4ae0dde1a30efc154c4879c15/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
}