/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteWrapper: typeof import('./src/components/SiteWrapper.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SiteWrapper: typeof import('./src/components/SiteWrapper.vue')['default']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
  const UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  const UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_6dc1142a6d2c38403226775cbfc1cfc5/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}